name: 04 - Using Actions

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Show repository structure
        run: |
          pwd
          find . -maxdepth 3 -type f | sort

      - name: Install dependencies
        shell: bash
        run: |
          cd "./04-using-actions/react-app"
          pwd
          ls -la
          npm ci
        # 0. Checkout the code from the repository
        # 1. Install deps of our react applications
        # 2. Execute automated test.
