name: 04- Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
<<<<<<< HEAD
            - name: Setup Node
              uses: actions/setup-node@v6
              with: 
                node-version: '24.x'
            - name: Install dependencies
              run: npm ci
       # 0. Checkout the code from the repository
        # 1. Install deps of our react applications
        # 2. Execute automated test
=======
            - name: Printing folders
              run: ls
       # 0. Checkout the code from the repository
        # 1. Install deps of our react applications
        # 2. Execute automated test
>>>>>>> 9e42bb1832586b22c39b44fe2ed2f4a08d5b55c4
