name: 06- Contexts

on: push

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                 echo "Event name is ${{ github.event_name }}"
                 echo : RefL {{ github.ref }}
                 echo: SHA: {{ github.sha }}
                 echo: ActorL {{ github.actor }}
                 echo "Workflow: {{ github.workflow }}"
                 echo: :Run ID: {{ github.run_id }}
                 echo "Run Number: {{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                 echo "Variable Value: ${{ vars.MY_VAR}}"